### ISSUE TITLE
Tweaking FOV

### ISSUE THREAD

**Issue by ainzz** [FazeDaFapper/s4-solar#1]
Hello,

I am trying to understand where can I tweak the distance from the crosshair to target on which the aim manager should lock.
I see a check for distance here https://github.com/FazeDaFapper/s4-solar/blob/36c868ca740ccf906c471e6e0e0cc3c69039efd3/solar/manager/aim_manager.cpp#L101
And the circle_diameter member here https://github.com/FazeDaFapper/s4-solar/blob/36c868ca740ccf906c471e6e0e0cc3c69039efd3/solar/manager/aim_manager.hpp#L37

Thanks

**Comment by FazeDaFapper** [comment]
The distance checks in aim_manager.cpp line 101 is a features which is a fix for an issue which happens if the enemy is above you and your camera setting is left/right. Without this fix your camera will rotate continuously because you can't look straight above you with camera setting left/right.

The circle diameter is to specify the range of the circle around your crosshair where the enemys get targeted. I could not include a drawing function for the circle because s4rem detects vtable and memory hooks.

I hope this helps you.

**Comment by ainzz** [comment]
The circle diameter is what I needed. Thanks for the explanation!
